### ISSUE TITLE
Regexp Error: regular expression too big

### ISSUE THREAD

**Issue by tinomen** [zevarito/mixpanel#1]
I have encountered this error on ajax calls that return good sized chunks of HTML. While they are big they really aren't too big, it's just something about the rails environment that is causing this to happen. Unfortunately I can't create a spec to duplicate the error but I was able to patch the gem in our production environment.

The backtrace from hoptaod:

[GEM_ROOT]/gems/mixpanel-0.6.1/lib/mixpanel/mixpanel_middleware.rb:29:in `gsub!'
[GEM_ROOT]/gems/mixpanel-0.6.1/lib/mixpanel/mixpanel_middleware.rb:29:in`update_response!'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/response.rb:155:in `each'
[GEM_ROOT]/gems/mixpanel-0.6.1/lib/mixpanel/mixpanel_middleware.rb:24:in`update_response!'
[GEM_ROOT]/gems/mixpanel-0.6.1/lib/mixpanel/mixpanel_middleware.rb:14:in `call'
[GEM_ROOT]/gems/rack-1.0.1/lib/rack/head.rb:9:in`call'
[GEM_ROOT]/gems/rack-1.0.1/lib/rack/methodoverride.rb:24:in `call'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/params_parser.rb:15:in`call'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/session/cookie_store.rb:93:in `call'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/failsafe.rb:26:in`call'
[GEM_ROOT]/gems/rack-1.0.1/lib/rack/lock.rb:11:in `call'
[GEM_ROOT]/gems/rack-1.0.1/lib/rack/lock.rb:11:in`synchronize'
[GEM_ROOT]/gems/rack-1.0.1/lib/rack/lock.rb:11:in `call'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/dispatcher.rb:106:in`call'

The nasty looking error message:

RegexpError: regular expression too big: /<script\ type='text\/javascript'>\n\ \ \/\/<![CDATA[\n\ \ \ \ function\ update_milestone_divs(obj){\n\ \ \ \ \ \ \$('#milestones').show();\n\ \ \ \ \ \ \$('#milestones').children('div').hide();\n\ \ \ \ \n\ \ \ \ \ \ divid\ =\ obj.options[obj.selectedIndex].value;\n\ \ \ \ \n\ \ \ \ \ \ divid\ =\ '#milestone_'\ +\ divid\n\ \ \ \ \ \ \$(divid).show()\n\ \ \ \ }\n\ \ \ \ \n\ \ \ \ \$(document).ready(function()\ {\n\ \ \ \ \ \ \/*\n\ \ \ \ \ \ *\ First\ step\ is\ to\ create\ title\ attributes\ for\ the\ rows\ in\ the\ table\n\ \ \ \ \ \ *\ This\ isn't\ needed\ if\ the\ required\ 'title'\ attribute\ is\ already\ set\ in\ the\ HTML\ in\ the\n\ \ \ \ \ \ *\ DOM\n\ \ \ \ \ \ *\/\n\ \ \ \ \ \ \$('#milestone_table\ tbody\ tr').each(\ function()\ {\n\ \ \ \ \ \ \ \ var\ sTitle;\n\ \ \ \ \ \ \ \ var\ nTds\ =\ \$('td',\ this);\n\ \ \ \ \ \ \ \ var\ sPic\ =\ \$(nTds[3]).text();\n\ \ \ \ \ \ \ \ var\ sName\ =\ \$(nTds[1]).text();\n\ \ \ \ \n\ \ \ \ \ \ \ \ sTitle\ =\ \ '<img\ src='\+sPic\+'\ height=60\ width=60\/><br>'+sName;\n\ \ \ \ \ \ \ \ this.setAttribute(\ 'title',\ sTitle\ );\n\ \ \ \ \ \ \n\ \ \ \ \ \ }\ );\n\ \ \ \ \n\ \ \ \ \ \ \/*\ Apply\ the\ tooltips\ *\/\n\ \ \ \ \ \ \$('#milestone_table\ tbody\ tr[title]').tooltip(\ {\n\ \ \ \ \ \ \ \ "delay":\ 0,\n\ \ \ \ \ \ \ \ "track":\ true,\n\ \ \ \ \ \ \ \ "fade":\ 250\n\ \ \ \ \ \ }\ );\n\ \ \ \ \n\ \ \ \ \ \ \/*\ Init\ DataTables\ *\/\n\ \ \ \ \ \ \$('#milestone_table').dataTable({\n\ \ \ \ \ \ \ \ "iDisplayLength":\ 10,\n\ \ \ \ \ \ \ \ "aaSorting":\ [[\ 2,\ "desc"\ ]],\n\ \ \ \ \ \ });\n\ \ \ \ });\n\ \ \/\/]]>\n<\/script>\n<style\ type='text\/css'>\n\ \ \/*<![CDATA[*\/\n\ \ \ \ #milestone_table\ {\n\ \ \ \ \ \ width:550px;\n\ \ \ \ \ \ \n\ \ \ \ }\n\ \ \ \ \n\ \ \ \ td\ {\ vertical-align:middle;}\n\ \ \ \ td.select\ {\ width:\ 50px;\ padding-left:10px;}\n\ \ \ \ td.titl

**Comment by zevarito** [comment]
A patch was submit to fix this issue.
