### ISSUE TITLE
How to set the user id?

### ISSUE THREAD

**Issue by miguelperez** [zevarito/mixpanel#10]
The javascript library allow you to set a visitors ID...

```
 mpmetrics.identify("USERNAME_HERE_OR_ANY_STRING")
```

I was looking at the code, and could not find this. Can this be doable with this implementation?

**Comment by LogicWolfe** [comment]
Yep, assuming you had this library initialized to a @mixpanel object you'd just use 
`@mixpanel.append_api("identify", "USERNAME_HERE_OR_ANY_STRING")`
