### ISSUE TITLE
Allow customization of mixpanel data sending

### ISSUE THREAD

**Issue by joevandyk** [zevarito/mixpanel#13]
Right now -- seems like there's two options for sending data to mixpanel from the server -- async with a new process, and via open(url).read.

It would be nice to be able to give Mixpanel a class that contained the logic for how to send the data to mixpanel.  For example, I'd like to use resque to do this async.

Has anyone started work on this?

**Comment by joevandyk** [comment]
See https://github.com/joevandyk/mixpanel/commit/8f611ac846f9352884475e838cf00bdc59dd6e22 for the start of the work.  Thoughts?

**Comment by joevandyk** [comment]
Yes, I started it -- it's pretty simple.  Hopefully I'll wrap it up tomorrow.

On Thu, Aug 11, 2011 at 7:12 PM, zevarito
reply@reply.github.com
wrote:

**Comment by zevarito** [comment]
To be honest I didn't agree about add async features to mixpanel gem. In my opinion that shouldn't be there, but many people using it asked for that feature.

Now I am seeing your changes and I think the approach that you've started is good, but my mind still doesn't believe about supporting async features built in.

Bellow is a Resque example, I never tried this piece of code and I am writing it from an airport without being close my eyes in the whole night/day :)

```
class MixpanelTrackEventJob
  @queue = :slow

  def mixpanel(request_env)
    Mixpanel.new(MIXPANEL_TOKEN, request_env)
  end

  def perform(name, params, request_env)
    mixpanel(request_env).track_event(name, params)
  end
end

class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])

     if @user.save
       MixpanelTrackEventJob.enqueue("Sign up", {:invited => params[:invited]}, request.env)
       redirect_to user_root_path
     else
       render :new
     end
  end
end
```

what do you think about this?
