### ISSUE TITLE
Middleware makes send_file return empty files

### ISSUE THREAD

**Issue by xxx** [zevarito/mixpanel#16]
Like the title says, adding the middleware makes all of our send_file calls return 0 byte files. Removing the middleware makes things work again.

I've attempted to insert it at different points of the middleware stack with no success.

**Comment by zevarito** [comment]
Can you tell me more about your stack so I can try to reproduce it?

**Comment by xxx** [comment]
Sure - We're on Rails 3.0.10 w/ Ruby 1.9.2-p180. The issue is repeatable in every environment, including dev and test. Please let me know if there's any more stack info you need.

**Comment by xxx** [comment]
Also, we're using unicorn for our app server.

**Comment by zevarito** [comment]
Hi,

Sorry for the delay, just checking if you still are running with this issue, I may have a few hours to start to work on it and just want to be sure.

Thanks.

**Comment by xxx** [comment]
yes, this is still happening with v1.0.0. Using ruby 1.9.2-p290 now also.

**Comment by zevarito** [comment]
Merged, thanks for the fix!
