### ISSUE TITLE
Use identify without javascript

### ISSUE THREAD

**Issue by smidwap** [zevarito/mixpanel#21]
I don't see how to set a unique identifier for a user without resorting to append_api. In our rails api's, we are not returning html pages but instead JSON responses. But we still need to be able to track events and tack on a user id (and name tag). Am I missing something in the documentation or is this just not doable?

**Comment by zevarito** [comment]
What do you mean exactly by unique identifier?

**Comment by smidwap** [comment]
Take a peek at the javascript api documentation:

http://mixpanel.com/api/docs/guides/integration/js#identify

You'll see that there is a way to set a user's id so that all data is tracked under that user id. How else can we track events for a specific user?

**Comment by smidwap** [comment]
Ah, let me clarify something:

The mixpanel HTTP api spec says that you can use distinct_id and mp_name_tag "special" properties to identify users. Is this the way to do it?

**Comment by zevarito** [comment]
I think if the Mixpanel API says that, it should be that way :)

Please if you encounter some api call/feature that you cannot use with this gem report it and we will implement it.

**Comment by smidwap** [comment]
Ok, no problem here. Everything works as expected.
