### ISSUE TITLE
Unable to setup the mixpanel gem correctly

### ISSUE THREAD

**Issue by mixellent** [zevarito/mixpanel#25]
I would really like to get Mixpanel to work on my rails app setup, but so far no luck. I may be missing something trivial here.

I have added the following code as suggested, to my config/environment.rb file:

Rails::Initializer.run do |config|
  config.middleware.use "Mixpanel::Tracker::Middleware", "MY_TOKEN_HERE", :async => true
end

Every time I try to run rails server, I get the following error:

<top (required)>': uninitialized constant Rails::Initializer (NameError)

I am using Rails 3.1.1

Thanks,

Michael

**Comment by zevarito** [comment]
Hello,

Take a look at your desired env config/environments/production.rb

It should have something like...

```
YourApplication.configure do

  # add mixpanel
  config.middleware.use "Mixpanel::Tracker::Middleware", "YOUR_MIXPANEL_API_TOKEN"
```

Alternatively you can create a new initializer file under config/initializers folder with the following code...

```
  YourApplication.config.middleware.use "Mixpanel::Tracker::Middleware", MIXPANEL_TOKEN
```

You should be fine with that, good luck!

**Comment by mixellent** [comment]
Thanks for the super quick reply Alvaro! It worked right after I followed your steps. Much appreciated :)
I hope this will be of use to others struggling to get this up and running.

**Comment by mixellent** [comment]
Alvaro,

Could you please clarify the following from the Readme:

To execute any javascript API call: @mixpanel.append_api("identify", "Unique Identifier")

Executing this method in a view prints out the following: [["identify", ["UNIQUE_ID_NUM"]]]

Do I need to put this code somewhere specific ? (controller/view/javascript tag) I am just not sure how I should use it.

Thanks in advance,

Michael

**Comment by mixellent** [comment]
Ok, sorry about this.

I understand now that the following code is actually being run in the background and an API call is being performed to MixPanel:

<% @mixpanel.append_api("identify", current_user.id) if current_user.present? %>
<% @mixpanel.append_api("name_tag", current_user.full_name) if current_user.present? %>

So I can basically apply the above code inside my application layout file for each page.

**Comment by zevarito** [comment]
```
#append_api
```

Will introduce a JS code that the browser client will execute, yes it is async but just because the client is taking care of the call and not the server.

If you want call mixpanel from the backend in a real async way you have two options...

1) Instantiate mixpanel with async param true.

2) User Resque or another message queue to do the job, example is in the README file.

Good luck!

**Comment by mixellent** [comment]
Thanks for the clarifications!

**Comment by perkins2099** [comment]
I'm having troubles getting this to work...

@mixpanel = Mixpanel::Tracker.new(ENV['MIXPANEL_DEV'], request.env, {async: true})

Wasn't able to do any calls directly to Mixpanel.  Then when I stopped my rails server it halted with some kind of sync error.

Also tried resque but he included class / worker wasn't working.  It said.. function enqueue not found for MixpanelTrackEventJob.

Any thoughts?

**Comment by zevarito** [comment]
@perkins2099 

Is that still being an issue for you?

What version of the gem are you using?

Does any version worked for you?

**Comment by zevarito** [comment]
Well if you don't answer the questions is really hard to help.

I don't know, but if the gem works without passing a custom env, I think you are probably doing something wrong.

**Comment by perkins2099** [comment]
Zevarito; I'm so sorry I was confused as to where I was replying to and thought it was MixPanel for some reason.  I apologize.

Let me try this again:
Version:
    mixpanel (2.0.1)
      escape
      json
      rack

I wasn't able to get any other version working though I was able to log track events but not the other stuff which required the javascript.  I was probably doing something wrong; perhaps not calling the middleware correctly.

**Comment by zevarito** [comment]
@perkins2099 

2.0.1 is one of the latest, may be there is a bug there, but no one has reported failures yet.

I suggest you to try with versions prior to 2.x.x.

Also if you want to copy/paste your implementation code here I can check if it is correct.
