### ISSUE TITLE
New Mixpanel Javascript API

### ISSUE THREAD

**Issue by rafaelcgo** [zevarito/mixpanel#27]
Guys,

Mixpanel has a new API, and the new javascript var is now mixpanel, instead of mpq.
They have a set of new features, like track_forms...

https://mixpanel.com/docs/integration-libraries/upgrading-the-javascript-library

How can we upgrade this? If you guys guide me I can try to make an pull request (never did one).

**Comment by zevarito** [comment]
I cannot look at this right now, but please go ahead try to fix it and do a
pull request.
Any question just drop it here.

Thanks!

2012/3/22 Rafael Oliveira <
reply@reply.github.com

> Guys,
> 
> Mixpanel has a new API, and the new javascript var is now mixpanel,
> instead of mpq.
> They have a set of new features, like track_forms...
> 
> https://mixpanel.com/docs/integration-libraries/upgrading-the-javascript-library
> 
> How can we upgrade this? If you guys guide me I can try to make an pull
> request (never did one).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/zevarito/mixpanel/issues/27

## 

Alvaro

**Comment by SachaG** [comment]
Any news about this? It would be great to update the gem!

**Comment by zevarito** [comment]
Gem updated to 2.0.0, I think that should work for you. Thanks.
