### ISSUE TITLE
Super Properties not showing up?

### ISSUE THREAD

**Issue by georgekitchit** [zevarito/mixpanel#28]
@mixpanel.append_api("register", {:test_super_property => "testing0"})

This is the way that I am registering super properties. All other functions seem to be working well (normal properties, events), but the super properties arent showing up. Is anyone else having a similar problem?

**Comment by zevarito** [comment]
Hi, @georgekitchit Do you still have this issue?

**Comment by georgekitchit** [comment]
Hey, yeah, but I talked to the mixpanel guys, turns out that super properties arent passed through the server API. I ended up  just passing the super properties in manually. I was thinking about overriding the track_event function and pulling the super properties out of the cookies, but it was easier to just manually put them in because i didn't want to do a regex / eval hack.

**Comment by zevarito** [comment]
closing then...
