### ISSUE TITLE
Filter request.env

### ISSUE THREAD

**Issue by brupm** [zevarito/mixpanel#31]
Rather than passing in the entire request.env we're trying to filter the hash and submit only the needed params as such:

```
@env = {}
["HTTP_X_REQUESTED_WITH", "HTTP_X_FORWARDED_FOR", "REMOTE_ADDR", "mixpanel_events"].each do |key|
  if env.has_key?(key)
    @env[key] = env[key]
  end
end
```

and instantiating as such:

```
Mixpanel::Tracker.new(AppConstants.mixpanel, @env, true)
```

It seems as we may be filtering too many params as the referrer isn't being tracked properly. Any idea which params we should not be filtering out in order to get the referrer tracker properly?

**Comment by zevarito** [comment]
@brupm are you deploying in Heroku?

**Comment by brupm** [comment]
Yes, cedar stack.

**Comment by zevarito** [comment]
@brupm Heroku uses HTTP_X_FORWARDED_FOR so I am not sure what is the deal.

Using the real env instead the custom one, it works ok?
