### ISSUE TITLE
Adding additional functions from Javascript SDK

### ISSUE THREAD

**Issue by rymodi** [zevarito/mixpanel#41]
I imagine others would find it useful if we added other functions that are included in the Javascript SDK, for example:
- Setting super properties using 'mixpanel.register'
- Giving users a name for viewing in the Streams section using 'mixpanel.register'

Right now you can get around it by just calling the 'append_api' method and passing the type. Would it be helpful for me to build out the other Javascript SDK functions into the gem?

**Comment by zevarito** [comment]
Hi @rymodi,

Any improvement to the library is appreciated, if you fell that are parts that need to be improved as the one you have mentions, please go ahead! Thanks!
