### ISSUE TITLE
distinct_id

### ISSUE THREAD

**Issue by jacquescrocker** [zevarito/mixpanel#43]
Might be worth documenting the need to send "distinct_id" as a property when sending events via resque. Otherwise mixpanel can't associate the event with a user.

thanks

**Comment by zevarito** [comment]
Hi @railsjedi,

Send distinct_id is a good practice, but the user should have been identified by IP address even when you perform async, it should be taked from the ENV. That didn't work for you?

**Comment by jacquescrocker** [comment]
ah, ok. I was testing it on local so the IP was 127.0.0.1

on production is IP address good enough to identify users though? 

thanks for the heads up!

**Comment by zevarito** [comment]
Well, it is an strategy, of-course if you have an ID identifying your users will be better to use that.

Cheers.
