### ISSUE TITLE
Does this plugin cover /engage endpoint for people tracking?

### ISSUE THREAD

**Issue by GBH** [zevarito/mixpanel#44]
I can do event tracking, but I don't see how I can push `people` data to mixpanel. https://mixpanel.com/docs/people-analytics/people-http-specification-insert-data

**Comment by zevarito** [comment]
@gbh is this what you are looking for?

https://github.com/zevarito/mixpanel#execute-javascript-api-call

**Comment by GBH** [comment]
@zevarito No. I want to do a call from the controller/model. There's no middleware involved.

**Comment by zevarito** [comment]
@GBH I am afraid you should do it manually, or add the feature to the gem.
