### ISSUE TITLE
Mixpanel 3.0 NameErrror

### ISSUE THREAD

**Issue by zh4ngx** [zevarito/mixpanel#48]
/.rvm/gems/ruby-1.9.3-p194/gems/activesupport-3.2.8/lib/active_support/inflector/methods.rb:230:in `block in constantize': uninitialized constant Mixpanel::Middleware (NameError)

My mixpanel init is ->

Rails.application.config.middleware.use "Mixpanel::Middleware", ENV['MIXPANEL_KEY'], persist: true

Following new Readme...is this incorrect?

**Comment by zevarito** [comment]
Hi @ZhangBanger,

Could you try the code bellow, I think it should work fine, please tell me how it was.

``` ruby
require 'mixpanel/middleware'
```

I've yanked the gem until get sometime to see what is happening, but pretty sure that middleware wasn't required when the tracker was. I've fix that soon.

Thanks!

**Comment by zh4ngx** [comment]
Sure, I'll give that a try. Thanks!

**Comment by zevarito** [comment]
@ZhangBanger I've pushed a quick fix for the issue you had. Please use version 3.0.1 of the gem, that should work without requiring the middleware manually, if it works, please come back and close the issue :)

Thanks!

**Comment by zh4ngx** [comment]
Thanks! Looks like this works for now, after I changed the function names to match 3.0's spec (any particular reason for changing them?)

**Comment by zevarito** [comment]
Well, it was a kind of code refactor.

Do you think README isn't helping users right now? Should it be changed? Thanks!

**Comment by zh4ngx** [comment]
I noticed the git changes to readme, but I was a little confused bc of the
glitch in 3.0.0. I think you should emphasize the new 3.0.0 syntax in the
readme.
