### ISSUE TITLE
Delayed_Job and this gem don't seem to play well together

### ISSUE THREAD

**Issue by jakemack** [zevarito/mixpanel#5]
There is a possibility that some other gem is helping cause the conflict as well, but I haven't had a chance to look into it. So, I'm going to paste my error here as well as our gemfile:

gem 'amazebot', '0.0.1', :git => 'git://github.com/amazebot/amazebot.git'
gem "mysql"
gem "rails"
gem "devise"
# gem "thinking-sphinx", '2.0.0.rc1', :require => 'thinking_sphinx'

gem 'thinking-sphinx', :require => 'thinking_sphinx', :git => "git://github.com/freelancing-god/thinking-sphinx.git", :branch => "rails3"
gem "will_paginate", "~> 3.0.pre2"
gem 'typus', :branch => '3-0-stable', :git => 'git://github.com/fesplugas/typus.git'
gem 'high_voltage'
gem "acts-as-taggable-on"
gem "haml"
gem 'jquery-rails'
gem 'paperclip'
gem 'formtastic', '~> 1.1.0'
gem 'inherited_resources', '1.1.2'
gem 'rails3-jquery-autocomplete'
gem 'aws-s3'
gem 'fastimage'
gem "delayed_job"
gem "mixpanel"
gem 'mechanize'

group :development do
  gem 'capistrano'
  gem 'capistrano-ext'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'forgery'
  gem 'rspec-rails'
end

group :test do
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'fakeweb'
  gem 'launchy'
  gem 'mocha'
  gem 'pickle'
  gem 'remarkable_activerecord', '4.0.0.alpha4'
end

group :production, :staging do
  gem 'passenger'
end

TypeError (can't convert nil into String):
  delayed_job (2.1.1) lib/delayed/yaml_ext.rb:15:in `value='
  delayed_job (2.1.1) lib/delayed/yaml_ext.rb:15:in`initialize'
  delayed_job (2.1.1) lib/delayed/yaml_ext.rb:15:in `new'
  delayed_job (2.1.1) lib/delayed/yaml_ext.rb:15:in`scalar'
  delayed_job (2.1.1) lib/delayed/yaml_ext.rb:15:in `block in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`call'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`quick_emit'
  delayed_job (2.1.1) lib/delayed/yaml_ext.rb:14:in `to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in`node_export'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in `add'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in`block (3 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in `each'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in`block (2 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in `map'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in`block in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `call'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `quick_emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:15:in`to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in `node_export'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in`add'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in `block (3 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in`each'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in `block (2 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in`map'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in `block in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`call'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`quick_emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:15:in `to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in`node_export'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in `add'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in`block (3 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in `each'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in`block (2 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in `map'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in`block in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `call'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `quick_emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:15:in`to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in `node_export'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in`add'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in `block (3 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in`each'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in `block (2 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in`map'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in `block in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`call'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`quick_emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:15:in `to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in`node_export'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in `add'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in`block (3 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in `each'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in`block (2 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in `map'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in`block in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `call'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `quick_emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:15:in`to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in `node_export'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in`add'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in `block (3 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in`each'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in `block (2 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in`map'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in `block in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`call'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`quick_emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:15:in `to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:43:in`node_export'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:43:in `add'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:43:in`block (3 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:42:in `each'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:42:in`block (2 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:41:in `map'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:41:in`block in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `call'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `quick_emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:40:in`to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in `node_export'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in`add'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:18:in `block (3 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in`each'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:17:in `block (2 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in`map'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:16:in `block in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`call'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`quick_emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:15:in `to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:95:in`node_export'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:95:in `add'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:95:in`block (3 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:94:in `each'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:94:in`block (2 levels) in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:93:in `map'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:93:in`block in to_yaml'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `call'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in`emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck.rb:401:in `quick_emit'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/syck/rubytypes.rb:89:in`to_yaml'
  delayed_job (2.1.1) lib/delayed/backend/base.rb:71:in `payload_object='
  activerecord (3.0.3) lib/active_record/base.rb:1559:in`block in attributes='
  activerecord (3.0.3) lib/active_record/base.rb:1555:in `each'
  activerecord (3.0.3) lib/active_record/base.rb:1555:in`attributes='
  activerecord (3.0.3) lib/active_record/base.rb:1406:in `initialize'
  activerecord (3.0.3) lib/active_record/base.rb:496:in`new'
  activerecord (3.0.3) lib/active_record/base.rb:496:in `create'
  delayed_job (2.1.1) lib/delayed/backend/base.rb:27:in`enqueue'
  delayed_job (2.1.1) lib/delayed/message_sending.rb:13:in `method_missing'
  app/controllers/assets_controller.rb:27:in`show'
  actionpack (3.0.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.0.3) lib/abstract_controller/base.rb:151:in`process_action'
  actionpack (3.0.3) lib/action_controller/metal/rendering.rb:11:in `process_action'
  actionpack (3.0.3) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  activesupport (3.0.3) lib/active_support/callbacks.rb:440:in `_run__3723442747058957340__process_action__1879061203195319015__callbacks'
  activesupport (3.0.3) lib/active_support/callbacks.rb:409:in`_run_process_action_callbacks'
  activesupport (3.0.3) lib/active_support/callbacks.rb:93:in `run_callbacks'
  actionpack (3.0.3) lib/abstract_controller/callbacks.rb:17:in`process_action'
  actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.0.3) lib/active_support/notifications.rb:52:in`block in instrument'
  activesupport (3.0.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (3.0.3) lib/active_support/notifications.rb:52:in`instrument'
  actionpack (3.0.3) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.0.3) lib/action_controller/metal/rescue.rb:17:in`process_action'
  actionpack (3.0.3) lib/abstract_controller/base.rb:120:in `process'
  actionpack (3.0.3) lib/abstract_controller/rendering.rb:40:in`process'
  actionpack (3.0.3) lib/action_controller/metal.rb:138:in `dispatch'
  actionpack (3.0.3) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.0.3) lib/action_controller/metal.rb:178:in `block in action'
  actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:62:in`call'
  actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:62:in `dispatch'
  actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:27:in`call'
  rack-mount (0.6.13) lib/rack/mount/route_set.rb:148:in `block in call'
  rack-mount (0.6.13) lib/rack/mount/code_generation.rb:93:in`block in recognize'
  rack-mount (0.6.13) lib/rack/mount/code_generation.rb:138:in `optimized_each'
  rack-mount (0.6.13) lib/rack/mount/code_generation.rb:92:in`recognize'
  rack-mount (0.6.13) lib/rack/mount/route_set.rb:139:in `call'
  actionpack (3.0.3) lib/action_dispatch/routing/route_set.rb:492:in`call'
  haml (3.0.24) lib/sass/plugin/rack.rb:41:in `call'
  mixpanel (0.6.1) lib/mixpanel/mixpanel_middleware.rb:12:in`call'
  warden (0.10.7) lib/warden/manager.rb:35:in `block in call'
  warden (0.10.7) lib/warden/manager.rb:34:in`catch'
  warden (0.10.7) lib/warden/manager.rb:34:in `call'
  actionpack (3.0.3) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  actionpack (3.0.3) lib/action_dispatch/middleware/head.rb:14:in `call'
  rack (1.2.1) lib/rack/methodoverride.rb:24:in`call'
  actionpack (3.0.3) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.0.3) lib/action_dispatch/middleware/flash.rb:182:in`call'
  actionpack (3.0.3) lib/action_dispatch/middleware/session/abstract_store.rb:149:in `call'
  actionpack (3.0.3) lib/action_dispatch/middleware/cookies.rb:295:in`call'
  activerecord (3.0.3) lib/active_record/query_cache.rb:32:in `block in call'
  activerecord (3.0.3) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in`cache'
  activerecord (3.0.3) lib/active_record/query_cache.rb:12:in `cache'
  activerecord (3.0.3) lib/active_record/query_cache.rb:31:in`call'
  activerecord (3.0.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:353:in `call'
  actionpack (3.0.3) lib/action_dispatch/middleware/callbacks.rb:46:in`block in call'
  activesupport (3.0.3) lib/active_support/callbacks.rb:415:in `_run_call_callbacks'
  actionpack (3.0.3) lib/action_dispatch/middleware/callbacks.rb:44:in`call'
  rack (1.2.1) lib/rack/sendfile.rb:107:in `call'
  actionpack (3.0.3) lib/action_dispatch/middleware/remote_ip.rb:48:in`call'
  actionpack (3.0.3) lib/action_dispatch/middleware/show_exceptions.rb:46:in `call'
  railties (3.0.3) lib/rails/rack/logger.rb:13:in`call'
  rack (1.2.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.0.3) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.2.1) lib/rack/lock.rb:11:in `block in call'
  <internal:prelude>:10:in`synchronize'
  rack (1.2.1) lib/rack/lock.rb:11:in `call'
  actionpack (3.0.3) lib/action_dispatch/middleware/static.rb:30:in`call'
  railties (3.0.3) lib/rails/application.rb:168:in `call'
  railties (3.0.3) lib/rails/application.rb:77:in`method_missing'
  railties (3.0.3) lib/rails/rack/log_tailer.rb:14:in `call'
  rack (1.2.1) lib/rack/content_length.rb:13:in`call'
  rack (1.2.1) lib/rack/handler/webrick.rb:52:in `service'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/webrick/httpserver.rb:111:in`service'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
  /Users/jakemack/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/webrick/server.rb:183:in`block in start_thread'

Rendered /Users/jakemack/.rvm/gems/ruby-1.9.2-p0@RightsGenie/gems/actionpack-3.0.3/lib/action_dispatch/middleware/templates/rescues/_trace.erb (2.4ms)
Rendered /Users/jakemack/.rvm/gems/ruby-1.9.2-p0@RightsGenie/gems/actionpack-3.0.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1734.4ms)
Rendered /Users/jakemack/.rvm/gems/ruby-1.9.2-p0@RightsGenie/gems/actionpack-3.0.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (1758.2ms)

**Comment by zevarito** [comment]
@jakemack, any update on this? could you found the issue? Thx

**Comment by jakemack** [comment]
Oddly enough, I haven't had much of an opportunity to look into it. We've changed focus a couple times since then so I've been busy with other things...not sure when I'll get around to it at this point.

**Comment by zevarito** [comment]
No worries. I have finished my self a round of hard work today, so used the
time to do a small thing on Mixpanel but I have to return now. :S

On Jun 20, 2011 6:54 PM, "jakemack" <
reply@reply.github.com>
wrote:

Oddly enough, I haven't had much of an opportunity to look into it. We've
changed focus a couple times since then so I've been busy with other
things...not sure when I'll get around to it at this point.

##
