### ISSUE TITLE
Add support for mixpanel.people.identify, which is different than mixpanel.identify

### ISSUE THREAD

**Issue by AhmedBelal** [zevarito/mixpanel#50]
There are two different identify methods in Mixpanel's API. I discovered this after calling append_identify followed by append_set.  My debugger shows: 
`MIXPANEL PEOPLE REQUEST (QUEUED, PENDING IDENTIFY):`

Although distinct id was correctly set for regular events, it was not set for people events. 

We need a  method _append_people_identify_ that calls `append 'people.identify', distinct_id`.

**Comment by AhmedBelal** [comment]
Clarification: It seems that you can call @mixpanel.append('people.identify', distinct_id) and distinct_ids will be set for both your events and your people.set requests but @mixpanel.append('identify', distinct_id) does not set distinct_ids for people requests.

**Comment by zevarito** [comment]
I'll close this in favor of #51
