### ISSUE TITLE
API Breakage and Changelog

### ISSUE THREAD

**Issue by mcolyer** [zevarito/mixpanel#54]
This isn't really a bug per se but If you change a public API can you make a note of it in the CHANGELOG? It makes upgrades go smoother (I just got bitten by track_event => track).

**Comment by zevarito** [comment]
Yes, sorry about that, I thought it was on README, did you check it out?

I will take a look as soon as I can. Thanks!

On Fri, Nov 9, 2012 at 5:04 PM, Matt Colyer notifications@github.comwrote:

> This isn't really a bug per se but If you change a public API can you make
> a note of it in the CHANGELOG? It makes upgrades go smoother (I just got
> bitten by track_event => track).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zevarito/mixpanel/issues/54.

## 

Alvaro
