### ISSUE TITLE
Error when starting thin server: `const_missing_from_s3_library': uninitialized constant Mixpanel::Tracker::Middleware

### ISSUE THREAD

**Issue by ghanpatel-old** [zevarito/mixpanel#56]
Hi,

While trying to start thin, I receive this error (in full below). Does anyone have a suggestion for me? Thanks!

/Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/aws-s3-0.6.3/lib/aws/s3/extensions.rb:212:in const_missing_from_s3_library': uninitialized constant Mixpanel::Tracker::Middleware (NameError)
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/activesupport-3.2.3/lib/active_support/inflector/methods.rb:229:inblock in constantize'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/activesupport-3.2.3/lib/active_support/inflector/methods.rb:228:in each'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/activesupport-3.2.3/lib/active_support/inflector/methods.rb:228:inconstantize'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/actionpack-3.2.3/lib/action_dispatch/middleware/stack.rb:24:in klass'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/actionpack-3.2.3/lib/action_dispatch/middleware/stack.rb:43:inbuild'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/actionpack-3.2.3/lib/action_dispatch/middleware/stack.rb:113:in block in build'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/actionpack-3.2.3/lib/action_dispatch/middleware/stack.rb:113:ineach'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/actionpack-3.2.3/lib/action_dispatch/middleware/stack.rb:113:in inject'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/actionpack-3.2.3/lib/action_dispatch/middleware/stack.rb:113:inbuild'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/railties-3.2.3/lib/rails/engine.rb:470:in app'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/railties-3.2.3/lib/rails/application/finisher.rb:31:inblock in module:Finisher'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/railties-3.2.3/lib/rails/initializable.rb:30:in instance_exec'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/railties-3.2.3/lib/rails/initializable.rb:30:inrun'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/railties-3.2.3/lib/rails/initializable.rb:55:in block in run_initializers'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/railties-3.2.3/lib/rails/initializable.rb:54:ineach'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/railties-3.2.3/lib/rails/initializable.rb:54:in run_initializers'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/railties-3.2.3/lib/rails/application.rb:136:ininitialize!'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/railties-3.2.3/lib/rails/railtie/configurable.rb:30:in method_missing'
from /Users/ghanpatel/Marqueed_Tintin/config/environment.rb:5:in'
from /Users/ghanpatel/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in require'
from /Users/ghanpatel/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:inrequire'
from /Users/ghanpatel/Marqueed_Tintin/config.ru:7:in block in <main>'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/rack-1.4.1/lib/rack/builder.rb:51:ininstance_eval'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/rack-1.4.1/lib/rack/builder.rb:51:in initialize'
from /Users/ghanpatel/Marqueed_Tintin/config.ru:1:innew'
from /Users/ghanpatel/Marqueed_Tintin/config.ru:1:in <main>'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:ineval'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/thin-1.5.0/lib/rack/adapter/loader.rb:33:in load'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/thin-1.5.0/lib/rack/adapter/loader.rb:42:infor'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/thin-1.5.0/lib/thin/controllers/controller.rb:169:in load_adapter'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/thin-1.5.0/lib/thin/controllers/controller.rb:73:instart'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/thin-1.5.0/lib/thin/runner.rb:187:in run_command'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/thin-1.5.0/lib/thin/runner.rb:152:inrun!'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/gems/thin-1.5.0/bin/thin:6:in <top (required)>'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/bin/thin:23:inload'
from /Users/ghanpatel/.rvm/gems/ruby-1.9.3-p327@marqueed/bin/thin:23:in `'

**Comment by ghanpatel-old** [comment]
Note: I've added the gem, included this code in my environments/dev.rb file:

# mixpanel

config.mixpanel_token = "XXXXXXXtoken-numbersXXXXX"
config.middleware.use "Mixpanel::Tracker::Middleware", Rails.application.config.mixpanel_token, :async => true, :insert_js_last => true

... thoughts?

**Comment by Breefield** [comment]
Really? This closed issue references a closed issue in mixpanel_client which is closed because of this issue.

**Comment by zevarito** [comment]
@Breefield just open it.

**Comment by tonatiuh** [comment]
I'm having this issue with MailView gem I think this is more about the aws-s3 gem.

**Comment by tonatiuh** [comment]
In my case the problem was appearing when I was running my specs, the problem was due to I only included the MailView gem in the development env.

**Comment by Sujan-Dey** [comment]
is it really solved???
