### ISSUE TITLE
Async option not working

### ISSUE THREAD

**Issue by jakemack** [zevarito/mixpanel#6]
I tested out the async code tonight and it didn't seem to work. The issue is line 62 of mixpanel.rb. In getting the path for the ruby executable, the current code has RbConfig::CONFIG['RUBY_SO_NAME']. This doesn't work for me on OS X Snow Leopard.

I did a little searching and couldn't find any RbConfig documentation, but I did find this:

http://ryanbigg.com/guides/initialization.html

In the second code box under section 1.2, Rails uses this line to get the known ruby executable:

RUBY = File.join(*RbConfig::CONFIG.values_at("bindir", "ruby_install_name")) + RbConfig::CONFIG["EXEEXT"]

The key difference is "ruby_install_name" instead of "RUBY_SO_NAME." Also, an exe extension is added in the case of this being run on Windows (on my Mac, the EXEEXT value is blank). I'll issue a pull request for this patch in a few moments...once I remember exactly how.

**Comment by zevarito** [comment]
I've merged your fix for this, so closing. Thanks.
