### ISSUE TITLE
Mixpanel break my javascript ..

### ISSUE THREAD

**Issue by jeremybdk** [zevarito/mixpanel#66]
Hi,
I am trying to get mixpanel working through javascript with the gem but I am getting a weird error in chrome or firefox : unexpected end of jquery.js

I believe there is an issue with the timing but don't know how to fix it here is how I do it : 

Pockiz::Application.configure do
    config.middleware.use "Mixpanel::Middleware", ENV['MIX_PANEL']
end

then in my application.html.erb : 

<% if user_signed_in? %>
       <%= javascript_tag do %>
       mixpanel.identify('<%= current_user.id%>');
       mixpanel.name_tag('<%= current_user.full_name%>');
       <% end %>
     <% end %>
      <script type="text/javascript">
              mixpanel.track('Page Viewed', {'Page Name' : document.title, 'URL' : window.location.pathname});
      </script>

I don't know what is going on but the error is Uncaught SyntaxError: Unexpected end of input 

Thanks in advance for you help,

Is there a way to queue in delayed jobs the javascript event ?

Thanks,

**Comment by zevarito** [comment]
Jeremy,

Sorry I have not clue about what is happening with your issue, sadly I am
under a terrible connection and couldn't access to internet for decent
periods.

Well, no, at first thought you can't do that with jobs and js events.

On Thu, Dec 27, 2012 at 3:36 PM, Jeremy Bod notifications@github.comwrote:

> Hi,
> I am trying to get mixpanel working through javascript with the gem but I
> am getting a weird error in chrome or firefox : unexpected end of jquery.js
> 
> I believe there is an issue with the timing but don't know how to fix it
> here is how I do it :
> 
> Pockiz::Application.configure do
> config.middleware.use "Mixpanel::Middleware", ENV['MIX_PANEL']
> end
> 
> then in my application.html.erb :
> 
> <% if user_signed_in? %>
> <%= javascript_tag do %>
> mixpanel.identify('<%= current_user.id%>');
> mixpanel.name_tag('<%= current_user.full_name%>');
> <% end %>
> <% end %>
> <br> mixpanel.track(&#39 https://github.com/zevarito/mixpanel/issues/39;Page
> Viewed&#39 https://github.com/zevarito/mixpanel/issues/39;, {&#39https://github.com/zevarito/mixpanel/issues/39;Page
> Name&#39 https://github.com/zevarito/mixpanel/issues/39; :
> document.title, &#39 https://github.com/zevarito/mixpanel/issues/39;URL&
> #39 https://github.com/zevarito/mixpanel/issues/39; :
> window.location.pathname});<br>
> 
> I don't know what is going on but the error is Uncaught SyntaxError:
> Unexpected end of input
> 
> Thanks in advance for you help,
> 
> Is there a way to queue in delayed jobs the javascript event ?
> 
> Thanks,
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/zevarito/mixpanel/issues/66.

## 

Alvaro
