### ISSUE TITLE
Anyway to update last seen / last login via gem / ruby?

### ISSUE THREAD

**Issue by twanlass** [zevarito/mixpanel#75]
I've moved all my events to the backend (queueing them up w/ delayed job) but one thing that seems to no longer be working is the user's last login / last seen when viewing people in the explore tab. 

Am I missing something? 

Thanks for the great work!

**Comment by twanlass** [comment]
Sorry - issue resolved. Unrelated to the gem, a few job workers became stuck and some events were not sent.

**Comment by zevarito** [comment]
Thanks for update this back.
