### ISSUE TITLE
Untitled

### ISSUE THREAD

**Issue by boazavital** [zevarito/mixpanel#8]

**Comment by zevarito** [comment]
> boazavital reported an issue:
> 
> I don't think gem works with < Ruby 1.9. Is this correct? If so please make a note of it >somewhere, both which ruby versions and which rails versions it works with. Thanks, >and great job!

It works with ruby 1.8.7 for example. You right, the Readme probably should include that information.

About which version of Rails I have to say that this is not a Rails plugin it is Rack based and should work with any Rack based framework/app.

If you give a try to it with your Ruby version and it doesn't work, please report the issue so we can fix it.

Thanks!
