### ISSUE TITLE
Directly tracking people events

### ISSUE THREAD

**Issue by alexslade** [zevarito/mixpanel#82]
It seems the people events only work when using the append_ middleware stuff. Is that right?

**Comment by Maciek416** [comment]
@heeton have you discovered the answer to this question? I'm also missing direct people event tracking.

**Comment by disbelief** [comment]
Maybe I'm misunderstanding the question, but it appears that `set`, `unset`, `set_once`, `increment`, `track_charge`, `delete` and `reset_charges` communicate directly with mixpanel without using the middleware.

**Comment by michaelglass** [comment]
@heeton @Maciek416: I can confirm what @disbelief said.  The engage endpoint is for people analytics. see person
